import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  SUPPORTED_CHAINS,
  TOKEN_CONTRACT_ADDRESSES,
} from "@avail-project/nexus-core";

const OUTPUT_PATH = resolve(
  new URL("../generated/token-contract-addresses.generated.ts", import.meta.url)
    .pathname
);

const chainNameById = new Map<number, string>(
  Object.entries(SUPPORTED_CHAINS).map(([name, id]) => [id, name])
);

const chainEntries = Object.entries(SUPPORTED_CHAINS)
  .map(([name, id]) => `  ${name}: ${id},`)
  .join("\n");

const tokenEntries = Object.entries(TOKEN_CONTRACT_ADDRESSES)
  .map(([symbol, chains]) => {
    const chainLines = Object.entries(chains)
      .map(([chainId, address]) => {
        const numericId = Number(chainId);
        const chainName = chainNameById.get(numericId);
        if (!chainName) {
          throw new Error(`Unknown chain id ${chainId} for token ${symbol}`);
        }
        return `    ${chainName}: '${address}' as const,`;
      })
      .join("\n");
    return `  ${symbol}: {\n${chainLines}\n  } as const,`;
  })
  .join("\n");

const content = `// Auto-generated by avail:gen. Do not edit directly.\n\nexport const SUPPORTED_CHAINS = {\n${chainEntries}\n} as const;\n\nexport const TOKEN_CONTRACT_ADDRESSES = {\n${tokenEntries}\n} as const;\n\nexport type ChainKey = keyof typeof SUPPORTED_CHAINS;\nexport type TokenSymbol = keyof typeof TOKEN_CONTRACT_ADDRESSES;\n\nexport const TOKEN_SYMBOLS = Object.keys(TOKEN_CONTRACT_ADDRESSES) as TokenSymbol[];\n\nexport const CHAINS = Object.keys(SUPPORTED_CHAINS) as ChainKey[];\n`;

writeFileSync(OUTPUT_PATH, content);
console.log(`Generated ${OUTPUT_PATH}`);
