import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import z from "zod";

import { DATA_SOURCES, OUTPUT_PATHS } from "./config";

const hermesSchema = z.array(
  z.object({
    id: z.string(),
    attributes: z.object({ symbol: z.string() }),
  })
);

const getFeedsFromHermes = async (hermesUrl: string) => {
  const result = await fetch(new URL("/v2/price_feeds", hermesUrl));
  return hermesSchema.parse(await result.json());
};

const [pythnet, pythtest] = await Promise.all([
  getFeedsFromHermes(DATA_SOURCES.hermes.pythnet),
  getFeedsFromHermes(DATA_SOURCES.hermes.pythtest),
]);

type Feed = z.infer<typeof hermesSchema>[number];

type SymbolLookup = Record<string, Record<string, string>>;

const sanitize = (value: string) => {
  const underscoreNormalized = value.replace(/[^A-Za-z0-9]+/g, "_");
  const collapsed = underscoreNormalized.replace(/_{2,}/g, "_");
  let trimmed = collapsed.replace(/^_|_$/g, "");

  if (/^\d/.test(trimmed)) {
    trimmed = `_${trimmed}`;
  }

  return trimmed;
};

const withHexPrefix = (value: string) =>
  value.startsWith("0x") ? value : `0x${value}`;

const buildLookup = (feeds: Feed[]): SymbolLookup => {
  const lookup: SymbolLookup = {};
  const defaultCategory = sanitize("Misc") || "Misc";

  for (const feed of feeds) {
    const [rawCategory, ...rawRest] = feed.attributes.symbol.split(".");
    const category = sanitize(rawCategory) || defaultCategory;

    const sanitizedParts = rawRest
      .map((part) => sanitize(part))
      .filter((part) => part.length > 0);

    let key = sanitizedParts.join("_");

    if (!key && rawCategory) {
      key = sanitize(rawCategory);
    }

    if (!key) {
      key = sanitize(feed.attributes.symbol);
    }

    if (!key) {
      key = `ID_${feed.id.slice(0, 8)}`;
    }

    lookup[category] ??= {};

    let finalKey = key;
    let dupeIndex = 1;

    while (
      finalKey in lookup[category] &&
      lookup[category][finalKey] !== feed.id
    ) {
      finalKey = `${key}_${dupeIndex++}`;
    }

    lookup[category][finalKey] = withHexPrefix(feed.id);
  }

  return lookup;
};

const sortKeys = <T>(value: Record<string, T>): Record<string, T> => {
  return Object.keys(value)
    .sort((a, b) => a.localeCompare(b))
    .reduce<Record<string, T>>((acc, key) => {
      acc[key] = value[key];
      return acc;
    }, {});
};

const sortLookup = (lookup: SymbolLookup): SymbolLookup => {
  const sortedCategories = sortKeys(lookup);

  return Object.entries(sortedCategories).reduce<SymbolLookup>(
    (acc, [category, entries]) => {
      acc[category] = sortKeys(entries);
      return acc;
    },
    {}
  );
};

const pythnetLookup = buildLookup(pythnet);
const pythtestLookup = buildLookup(pythtest);

const generatorSourcePath = OUTPUT_PATHS.pricefeed.generatorSource;
const generatedDir = OUTPUT_PATHS.pricefeed.directory;
const outputEntrypointPath = OUTPUT_PATHS.pricefeed.entrypoint;

const writeNetwork = async (networkName: string, lookup: SymbolLookup) => {
  const networkDir = path.join(generatedDir, networkName);
  await mkdir(networkDir, { recursive: true });

  const sortedLookup = sortLookup(lookup);

  const categoryEntries = Object.entries(sortedLookup);
  const exportLines: string[] = [
    `// This file is auto-generated by ${generatorSourcePath}.`,
    `// Run "bun run ./src/pyth" to refresh these files.`,
    "",
  ];

  await Promise.all(
    categoryEntries.map(async ([category, entries]) => {
      const categoryFilePath = path.join(networkDir, `${category}.ts`);
      const fileContents = `// This file is auto-generated by ${generatorSourcePath}.\n// Network: ${networkName}, Category: ${category}\n// Run "bun run ./src/pyth" to refresh this file.\n\nexport const ${category} = ${JSON.stringify(
        entries,
        null,
        2
      )} as const;\n`;

      await writeFile(categoryFilePath, fileContents, "utf8");
      exportLines.push(`export { ${category} } from "./${category}";`);
    })
  );

  exportLines.push("");

  const indexPath = path.join(networkDir, "index.ts");
  await writeFile(indexPath, exportLines.join("\n"), "utf8");
};

await rm(generatedDir, { recursive: true, force: true });
await mkdir(generatedDir, { recursive: true });

await Promise.all([
  writeNetwork("pythnet", pythnetLookup),
  writeNetwork("pythtest", pythtestLookup),
]);

const entryFileLines = [
  `// This file is auto-generated by ${generatorSourcePath}.`,
  `// Run "bun run ./src/pyth" to refresh these files.`,
  "",
  `export * as pythnet from "./generated/pythnet";`,
  `export * as pythtest from "./generated/pythtest";`,
  "",
  `// For optimal tree-shaking, import categories directly, e.g.,`,
  `//   import { Crypto } from "./pyth/generated/pythnet";`,
  `//   const feedId = Crypto.ETH_USD;`,
  "",
];

await writeFile(outputEntrypointPath, entryFileLines.join("\n"), "utf8");
