import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { DATA_SOURCES, OUTPUT_PATHS } from "./config";

const generatorSourcePath = OUTPUT_PATHS.addresses.generatorSource;

const toPascalCase = (value: string) =>
  value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");

const toSafeIdentifier = (value: string, fallback: string) => {
  const cleaned = value.replace(/[^A-Za-z0-9]/g, "_");
  const noLeadingDigits = cleaned.replace(/^[^A-Za-z_]+/, "");
  if (noLeadingDigits.length > 0) {
    return noLeadingDigits;
  }

  const safeFallback = fallback.replace(/[^A-Za-z0-9]/g, "_").replace(
    /^[^A-Za-z_]+/,
    ""
  );
  return safeFallback || `Identifier_${Math.random().toString(16).slice(2)}`;
};

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const storeDir = DATA_SOURCES.contractManager.store;
const outputRoot = OUTPUT_PATHS.addresses.directory;
const aggregatorPath = OUTPUT_PATHS.addresses.entrypoint;

const baseHeaderLines = [
  `// This file is auto-generated by ${generatorSourcePath}.`,
  `// Run "bun run ./src/pyth" to refresh these files.`,
];

const headerComment = [...baseHeaderLines, ""].join("\n");

const getJsonFiles = async (dir: string) => {
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
};

const main = async () => {
  const storeEntries = await readdir(storeDir, { withFileTypes: true });
  const folders = storeEntries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  await rm(outputRoot, { recursive: true, force: true });
  await mkdir(outputRoot, { recursive: true });

  const aggregatorLines = [headerComment];

  for (const folder of folders) {
    const sourceDir = path.join(storeDir, folder);
    const outputDir = path.join(outputRoot, folder);
    await mkdir(outputDir, { recursive: true });

    const files = await getJsonFiles(sourceDir);
    const exportLines: string[] = [headerComment];

    for (const file of files) {
      const basename = path.basename(file, ".json");
      const identifier = toSafeIdentifier(basename, basename);
      const sourcePath = path.join(sourceDir, file);
      const fileContents = await readFile(sourcePath, "utf8");
      const data = JSON.parse(fileContents);

      if (!Array.isArray(data)) {
        throw new Error(
          `Expected array in ${sourcePath}, received ${typeof data}`
        );
      }

      const entries: Array<{ key: string; value: unknown }> = [];

      const keyCandidates = ["chain", "id", "key", "name", "cluster", "type"];

      for (let index = 0; index < data.length; index++) {
        const entry = data[index];
        if (typeof entry !== "object" || entry === null) {
          throw new Error(
            `Invalid entry at index ${index} in ${sourcePath}. Expected object.`
          );
        }

        let selectedKey: string | undefined;
        for (const candidate of keyCandidates) {
          const value = (entry as Record<string, unknown>)[candidate];
          if (typeof value === "string" && value.length > 0) {
            selectedKey = toSafeIdentifier(value, `${identifier}_${index}`);
            break;
          }
        }

        if (!selectedKey) {
          selectedKey = toSafeIdentifier(`${identifier}_${index}`, `Entry${index}`);
        }

        let uniqueKey = selectedKey;
        let attempt = 1;
        while (entries.some(({ key }) => key === uniqueKey)) {
          uniqueKey = `${selectedKey}_${attempt++}`;
        }

        entries.push({ key: uniqueKey, value: entry });
      }

      const outputFilePath = path.join(outputDir, `${identifier}.ts`);
      const fileHeader = [
        ...baseHeaderLines,
        `// Source: ${path.relative(moduleDir, sourcePath)}`,
        "",
      ].join("\n");

      const entryLines = entries
        .map(({ key, value }) => {
          const serialized = JSON.stringify(value, null, 2)
            .split("\n")
            .map((line, lineIndex) =>
              lineIndex === 0 ? line : `  ${line}`
            )
            .join("\n");
          return `  ${key}: ${serialized}`;
        })
        .join(",\n\n");

      const outputContents = `${fileHeader}\nexport const ${identifier} = {\n${entryLines}\n} as const;\n`;

      await writeFile(outputFilePath, outputContents, "utf8");
      exportLines.push(`export { ${identifier} } from "./${identifier}";`);
    }

    exportLines.push("");

    const indexPath = path.join(outputDir, "index.ts");
    await writeFile(indexPath, exportLines.join("\n"), "utf8");

    const namespace = toPascalCase(folder) || toSafeIdentifier(folder);
    aggregatorLines.push(
      `export * as ${namespace} from "./generated/addresses/${folder}";`
    );
  }

  aggregatorLines.push(
    "",
    `// For tree-shaking, import specific modules directly, e.g.,`,
    `//   import { EvmPriceFeedContracts } from "./pyth/generated/addresses/contracts";`,
    `//   const address = EvmPriceFeedContracts.ethereum.address;`
  );
  aggregatorLines.push("");

  await writeFile(aggregatorPath, aggregatorLines.join("\n"), "utf8");

  console.log(`Generated address modules under ${outputRoot}`);
};

await main();
