// This file is auto-generated by src/pyth/scripts/01-addresses.ts.
// Run "bun run ./src/pyth" to refresh these files.

export * as Chains from "./generated/addresses/chains";
export * as Contracts from "./generated/addresses/contracts";
export * as Tokens from "./generated/addresses/tokens";
export * as Vaults from "./generated/addresses/vaults";

// For tree-shaking, import specific modules directly, e.g.,
//   import { EvmPriceFeedContracts } from "./pyth/generated/addresses/contracts";
//   const address = EvmPriceFeedContracts.ethereum.address;
