// This file is auto-generated by src/pyth/scripts/00-pricefeed.ts.
// Run "bun run ./src/pyth" to refresh these files.

export * as pythnet from "./generated/pythnet";
export * as pythtest from "./generated/pythtest";

// For optimal tree-shaking, import categories directly, e.g.,
//   import { Crypto } from "./pyth/generated/pythnet";
//   const feedId = Crypto.ETH_USD;
